<h1 class="text-center my-5">Bienvenue sur le blog Lorem Ipsum PHP</h1>

<?php foreach($allPosts as $post): ?>
    <div class="card my-4">
        <h5 class="card-header"><?= $post["name"] ?></h5>
        <div class="card-body">
            <h5 class="card-title"><?= $post["title"] ?></h5>
            <p class="card-text"><?= $post["content"] ?></p>
        </div>
        <div class="card-footer text-muted d-flex justify-content-between">
            <div>
                <?= $post["username"] ?>
            </div>
            <div>
                <?= $post["creation_date"] ?>
            </div>
        </div>
    </div>
<?php endforeach ?>

<!-- PAGINATION -->
<ul class="pagination justify-content-center">
    <li class="page-item <?php if($page == 1): ?>disabled<?php endif ?>"><a class="page-link" href="index.php?page=1">Première page</a></li>
    
    <li class="page-item <?php if($page == 1): ?>disabled<?php endif ?>"><a class="page-link" href="index.php?page=<?= $pagePrecedente ?>">Précédent</a></li>

    <?php for($i = 1 ; $i <= $nbrPages ; $i++): ?>
        <li class="page-item"><a class="page-link" href="index.php?page=<?= $i ?>"><?= $i ?></a></li>
    <?php endfor ?>

    <li class="page-item <?php if($page == $nbrPages): ?>disabled<?php endif ?>"><a class="page-link" href="index.php?page=<?= $pageSuivante ?>">Suivant</a></li>

    <li class="page-item <?php if($page == $nbrPages): ?>disabled<?php endif ?>"><a class="page-link" href="#">Dernière page</a></li>
  </ul>