<h1 class="text-center my-5">Ajouter un article</h1>



<form method="post" action="newArticle.php">
  <fieldset>
    <legend>Tous les champs doivent être remplis :</legend>
    <div class="mb-3">
      <label for="title" class="form-label">Titre</label>
      <input type="text" id="title" name="title" class="form-control" require>
    </div>
    <div class="mb-3">
      <label for="content" class="form-label">Votre texte</label>
      <input type="textarea" id="content" name="content" class="form-control" style="height: 100px" require>
    </div>
    <div class="mb-3">
      <label for="category_id" class="form-label">Catégorie</label>
      <select id="category_id" name="category_id" class="form-select" require>
          <?php foreach($categories as $categorie): ?>
        <option value='<?= $categorie["id"] ?>'><?= $categorie["name"] ?></option>
        <?php endforeach ?>
      </select>
    </div>
    <button type="submit" class="btn btn-primary">Valider</button>
  </fieldset>
</form>